---

- name: 
  yum: 
    name: http://rpm.squirrel5.com/squirrel5-repo-1.0-1.x86_64.rpm
    state: installed 

- name: Install Squirrel Repo 
  yum: 
    name: "{{ item }}" 
    state: present 
  with_items: 
    - libselinux-python
    - collectd 
    - collectd-rrdtool

- name: Template Files copied along
  template: 
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    
- name: Template through collectd_configo 
  template: 
    src: collectd.conf.j2 
    dest: /etc/collectd.conf 
    owner: root
    group: root 
    mode: 0644

- name: Start collectd 
  service: 
    name: collectd 
    state: started 
    enabled: yes 

